[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -w 1 -b 0.0.0.0:$PORT web:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
